

export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SECCESS: "LOGIN_SECCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_USER: "LOGIN_USER",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SECCESS: "LOGOUT_SECCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE"

}
export const signupConstants = {
    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SECCESS: "SIGNUP_SECCESS",
    SIGNUP_FAILURE: "SIGNUp_FAILURE"
    
}


export const categoryConstants = {
    GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
    GET_CATEGORY_SECCESS: "GET_CATEGORY_SECCESS",
    GET_CATEGORY_FAILURE: "GET_CATEGORY_FAILURE",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SECCESS: "ADD_CATEGORY_SECCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SECCESS: "DELETE_CATEGORY_SECCESS",
    DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE"

}


export const productConstants = {
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SECCESS: "GET_PRODUCT_SECCESS",
    GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SECCESS: "ADD_PRODUCT_SECCESS",
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SECCESS: "DELETE_PRODUCT_SECCESS",
    DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE"

}

export const UserConstants={

    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SECCESS: "GET_USER_SECCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",
}

export const OrdersConstants={
    GET_ORDERS_SECCESS: "GET_ORDERS_SECCESS",
    GET_ORDERS_FAILURE: "GET_ORDERS_FAILURE",
    DELETE_ORDERS_SECCESS: "DELETE_ORDERS_SECCESS",
    DELETE_ORDERS_FAILURE: "DELETE_ORDERS_FAILURE",
}