export const categoryConstants= {
    GET_CATEGORY_REQUEST:"GET_CATEGORY_REQUEST",
    GET_CATEGORY_SECCESS:"GET_CATEORY_SECCESS",
    GET_CATEGORY_FAILURE:"GET_CATEGORY_FAILURE"

}

export const productConstants = {
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SECCESS: "GET_PRODUCT_SECCESS",
    GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",
    GET_PRODUCT_BY_CATEGORY_ID_REQUEST:"GET_PRODUCT_BY_CATEGORY_ID_REQUEST",
    GET_PRODUCT_BY_CATEGORY_ID_SECCESS:"GET_PRODUCT_BY_CATEGORY_ID_SECCESS",
    GET_PRODUCT_BY_CATEGORY_ID_FAILURE:"GET_PRODUCT_BY_CATEGORY_ID_FAILURE"

}

export const orderConstants={
    ADD_ORDER_SECCESS: "ADD_PRODUCT_SECCESS",
    ADD_ORDER_FAILURE: 'ADD_PRODUCT_FAILURE',
}